### ISSUE TITLE
Diagonal traversal

### ISSUE THREAD

**Issue by Lewiscowles1986** [beefsack/go-astar#7]
Do you think it would be desirable to add diagonal traversal to this algorithm?

**Comment by beefsack** [comment]
Hi @Lewiscowles1986, it's possible to implement diagonal traversal by implementing [`Pather`](https://github.com/beefsack/go-astar/blob/4ecf9e3044829f1e2d9eba4ff26295a2bbb9b2cd/astar.go#L9). The consumer of the library needs to implement `Pather` for their own world representation.

An example of implementing `Pather` orthogonally is in [`pather_test.go`](https://github.com/beefsack/go-astar/blob/master/pather_test.go), however it should be trivial to make an implementation which also supported diagonals.
